project:
  type: website
  output-dir: docs

website:
  title: "Classe ABNT com LaTeX"
  navbar:
    background: "#2e3f58"

format:
  bookup-html+lightonly:
    embed-fonts: true
    css: styles.css
    toc: true
    code-tools: true
    code-overflow: wrap
execute:
  warning: false
jupyter: python3